import type { SlashCommandItem } from "@/lib/editor/slashCommandTypes";

export const extendedSlashCommands: SlashCommandItem[] = [
  // ── 개발자 특화 (obnofi 전용) ─────────────────────────────────
  {
    id: "apiTester",
    title: "API 테스터",
    description: "HTTP 요청 테스트",
    icon: "Zap",
    category: "developer",
    isObnofi: true,
    keywords: ["api", "http", "rest", "테스터"],
  },
  {
    id: "githubEmbed",
    title: "GitHub 임베드",
    description: "Repository, Issue, PR, Gist 링크 임베드",
    icon: "GitGraph",
    category: "developer",
    isObnofi: true,
    keywords: ["github", "repo", "repository", "issue", "pr", "gist", "깃허브", "임베드"],
  },
  {
    id: "githubGist",
    title: "GitHub Gist",
    description: "Gist 코드 스니펫 임베드",
    icon: "GitGraph",
    category: "developer",
    isObnofi: true,
    keywords: ["gist", "github", "code", "스니펫"],
  },
  {
    id: "githubIssue",
    title: "GitHub 이슈",
    description: "이슈 링크 임베드",
    icon: "GitPullRequest",
    category: "developer",
    isObnofi: true,
    keywords: ["issue", "github", "이슈"],
  },
  {
    id: "githubPull",
    title: "GitHub PR",
    description: "Pull request 링크 임베드",
    icon: "GitPullRequest",
    category: "developer",
    isObnofi: true,
    keywords: ["pr", "pull request", "github", "풀리퀘스트"],
  },

  // ── 고급 블록 ────────────────────────────────────────────────
  {
    id: "toggleH1",
    title: "제목 토글 1",
    description: "접을 수 있는 제목 1",
    icon: "ChevronDown",
    category: "advanced",
    isDisabled: true,
    keywords: ["toggle", "heading", "토글", "제목"],
  },
  {
    id: "toggleH2",
    title: "제목 토글 2",
    description: "접을 수 있는 제목 2",
    icon: "ChevronDown",
    category: "advanced",
    isDisabled: true,
    keywords: ["toggle", "heading", "토글", "제목"],
  },
  {
    id: "toggleH3",
    title: "제목 토글 3",
    description: "접을 수 있는 제목 3",
    icon: "ChevronDown",
    category: "advanced",
    isDisabled: true,
    keywords: ["toggle", "heading", "토글", "제목"],
  },
  {
    id: "columns2",
    title: "2열 레이아웃",
    description: "2열 나란히 레이아웃",
    icon: "Columns2",
    category: "advanced",
    keywords: ["column", "layout", "2열"],
  },
  {
    id: "columns3",
    title: "3열 레이아웃",
    description: "3열 나란히 레이아웃",
    icon: "Columns3",
    category: "advanced",
    keywords: ["column", "layout", "3열"],
  },
  {
    id: "math",
    title: "수학 공식",
    description: "LaTeX 수식 블록 렌더링",
    icon: "Sigma",
    category: "advanced",
    keywords: ["math", "latex", "formula", "수식"],
  },
  {
    id: "button",
    title: "버튼",
    description: "클릭 가능한 버튼",
    icon: "Square",
    category: "advanced",
    keywords: ["button", "버튼"],
  },
  {
    id: "pageLink",
    title: "페이지 링크",
    description: "다른 페이지로 링크",
    icon: "Link",
    category: "advanced",
    keywords: ["page", "link", "페이지", "링크"],
  },
  {
    id: "template",
    title: "템플릿",
    description: "재사용 가능한 콘텐츠 블록",
    icon: "LayoutTemplate",
    category: "advanced",
    keywords: ["template", "템플릿"],
  },
  {
    id: "template-meeting",
    title: "회의록",
    description: "안건, 메모, 액션 아이템 양식",
    icon: "ClipboardList",
    category: "advanced",
    keywords: ["template", "meeting", "회의", "회의록", "템플릿"],
  },
  {
    id: "template-project",
    title: "프로젝트 브리프",
    description: "범위, 목표, 결과물 정의 양식",
    icon: "FileText",
    category: "advanced",
    keywords: ["template", "project", "프로젝트", "브리프", "템플릿"],
  },
  {
    id: "template-weekly",
    title: "주간 플래너",
    description: "이번 주 할일과 일정 양식",
    icon: "CalendarDays",
    category: "advanced",
    keywords: ["template", "weekly", "주간", "플래너", "템플릿"],
  },

  // ── 페이지 ──────────────────────────────────────────────────
  {
    id: "subPage",
    title: "하위 페이지",
    description: "현재 페이지 안에 새 페이지 만들기",
    icon: "FileText",
    category: "page",
    keywords: ["page", "subpage", "하위", "페이지", "서브"],
  },

  // ── Clearing / MindGrove ───────────────────────────────────
  {
    id: "canvas",
    title: "Clearing",
    description: "인라인 Clearing 보드 삽입",
    icon: "Palette",
    category: "canvas",
    keywords: ["clearing", "canvas", "board", "화이트보드", "캔버스"],
  },
  {
    id: "mindMap",
    title: "Mind Map",
    description: "인라인 Mind Map 삽입",
    icon: "Network",
    category: "canvas",
    keywords: ["mindmap", "mind map", "map", "mindgrove", "마인드맵"],
  },

  // ── 임베드 ──────────────────────────────────────────────────
  {
    id: "embed",
    title: "링크 임베드",
    description: "URL을 임베드로 삽입",
    icon: "Globe",
    category: "embed",
    keywords: ["embed", "url", "link", "임베드"],
  },
  {
    id: "googleDrive",
    title: "Google Drive",
    description: "구글 드라이브 파일 임베드",
    icon: "HardDrive",
    category: "embed",
    keywords: ["google", "drive", "구글"],
  },
  {
    id: "tweet",
    title: "Tweet",
    description: "트위터/X 게시물 임베드",
    icon: "MessageSquare",
    category: "embed",
    keywords: ["tweet", "twitter", "x", "트위터"],
  },

  // ── 인라인 ──────────────────────────────────────────────────
  {
    id: "mention",
    title: "사용자 멘션",
    description: "@이름으로 사용자 언급",
    icon: "AtSign",
    category: "inline",
    isDisabled: true,
    keywords: ["mention", "user", "멘션"],
  },
  {
    id: "pageMention",
    title: "페이지 멘션",
    description: "[[페이지명]]으로 페이지 링크",
    icon: "FileText",
    category: "inline",
    keywords: ["page", "mention", "link", "페이지"],
  },
  {
    id: "dateReminder",
    title: "날짜 / 리마인더",
    description: "@날짜로 날짜 삽입",
    icon: "CalendarDays",
    category: "inline",
    isDisabled: true,
    keywords: ["date", "reminder", "날짜", "리마인더"],
  },
  {
    id: "emoji",
    title: "이모지",
    description: ":이름:으로 이모지 삽입",
    icon: "Smile",
    category: "inline",
    isDisabled: true,
    keywords: ["emoji", "이모지"],
  },
  {
    id: "inlineMath",
    title: "인라인 수식",
    description: "인라인 수학 공식",
    icon: "Sigma",
    category: "inline",
    isDisabled: true,
    keywords: ["math", "formula", "수식", "인라인"],
  },
];
