ALTER TABLE "Page"
ADD COLUMN "heading1FontSizePt" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "heading2FontSizePt" INTEGER NOT NULL DEFAULT 23,
ADD COLUMN "heading3FontSizePt" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN "heading4FontSizePt" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN "heading5FontSizePt" INTEGER NOT NULL DEFAULT 14;
